name: Release Please
on:
  workflow_call:
    secrets:
      GH_APP_IDENTIFICATION_RELEASER:
        required: true
    inputs:
      gcp-auth:
        type: string
        required: true
        default: ${{ vars.GCP_AUTH }}
      command:
        type: string
        required: false
        default: "manifest"
        description: |-
          release-please command to run. Defaults to 'manifest'.
    outputs:
      releases_created:
        value: ${{ jobs.release.outputs.releases_created }}
        description: |-
          If any releases have been created by release-please.
      paths_released:
        value: ${{ jobs.release.outputs.paths_released }}
        description: |-
          JSON array which contains all paths which have been released.
          Example: `["packages/package-a", "packages/package-b"]`
jobs:
  release:
    name: release-please
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup GCP Authentication
        uses: abinnovision/actions/actions/setup-gcp@master
        with:
          auth: ${{ inputs.gcp-auth }}
      - id: token
        name: Generate GitHub App token
        uses: abinnovision/actions/actions/get-github-app-token@master
        with:
          identification: ${{ secrets.GH_APP_IDENTIFICATION_RELEASER }}
      - id: release
        name: Run release-please
        uses: google-github-actions/release-please-action@v3
        with:
          command: ${{ inputs.command }}
          token: ${{ steps.token.outputs.token }}
